# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190624_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='users_who_liked',
            field=models.ManyToManyField(related_name='quotes_liked', to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_likes', to='myapp.User'),
        ),
    ]
